var cmds = [
	{
		"cmd":"GetValue",
		"cmdDes":" Get object properties and save to buffer<br>	" +
				"Object properties can be access:<br>	" +
				"	ID：uique ID generated by system<br>	" +
				"	UserID：user input ID<br>	" +
				"	Name：object name set by user<br>	" +
				"	BundleId：model ID<br>	" +
				"	PropertyDict：user-defined properties, can be access by path such as \"PropertyDict/ObjectType\", will access all user-defined properties if no path is given<br>	" +
				"	MoniterData/RealTimeData: monitoring data, save as PropertyDict, can be access by path, will access all monitoring properties if no path is given<br>	" +
				"",
		"parameterInherit":"ObjectCommand",
		"parameters":[
			{ "parameter":"path", "des":"property path, for instance, \"PropertyDict/ObjectType\"，can also be used to access user-define property", "required":true},
			{ "parameter":"toBuffer", "des":"buffer to save result" , "required":true}
		],
		"examples":[
			{
				"name":"get user-define value of a object",
				"context":	'' +
						'{<br>' +
						'	"cmd": "GetValue", <br>' +
						'	"uid":"obj01" <br>' +
						'	"path":"PropertyDict/ObjectType",<br>' +
						'	"toBuffer":"resultBuffer" <br>' +
						'}'	
			},
			{
				"name":"get one monitoring data",
				"context":	'' +
						'{<br>' +
						'	"cmd": "GetValue", <br>' +
						'	"uid":"obj01" <br>' +
						'	"path":"MoniterData/RealTimeData/Temperature",<br>' +
						'	"toBuffer":"resultBuffer" <br>' +
						'}'	
			},				
			{
				"name":"get all monitoring data",
				"context":	'' +
						'{<br>' +
						'	"cmd": "GetValue", <br>' +
						'	"uid":"obj01" <br>' +
						'	"path":"MoniterData/RealTimeData",<br>' +
						'	"toBuffer":"resultBuffer" <br>' +
						'}'	
			}			
			
		]
	},
	{
		"cmd":"SetValue",
		"cmdDes":"Set object property" ,
		"parameterInherit":"ObjectCommand",
		"parameters":[
			{ "parameter":"path", "des":"Property path, for instance, \"PropertyDict/ObjectType\"", "required":true},
			{ "parameter":"value", "des":"value to be assign to property<br>	" +
					"Note: system use strong type internally. String, number or boolean can be used as normal, for other data type, the name of data type need to be specified.<br>	" +
					"for instance, vector3，color should be wrote as<br>	" +
					"{\"Vector3\":[1,0,0]}<br>	" +
					"{\"Vector2\":[1,0]}<br>	" +
					"{\"Color\":[1,0,0,1]}<br>	", "required":true},
		],
		"examples":[
			{
				"name":"Set Object Name",
				"context":	'' +
						'{<br>' +
						'	"cmd": "SetValue", <br>' +
						'	"uid":"obj01",<br>' +
						'	"path":"Name",<br>' +
						'	"value":"Camera01"<br>' +
						'}'	
			}
		]
	},
	{
		"cmd":"CallMethod",
		"cmdDes":"Call Object Method<br>	" +
				"Object Method List:<br>	" +
				"	Object in Scene：<br>	" +
				"		show：if visible <br>	" +
				"		GetCenter：get object center <br>	" +
				"	Timer Object<br>	" +
				"		reset：reset timer<br>	" +		
				"		setStartTime：set timer start time[2015, 8,12,16,15,22,0]<br>	" +				
				"		setPeriod：set timer run duration[0,0,0,30,0]<br>	" +				
				"		start：start timer<br>	" +				
				"		pause：pause timer<br>	" +			
				"		setSpeed：set timer run speed<br>	" 	+
				"",
		"parameterInherit":"ObjectCommand",
		"parameters":[
			{ "parameter":"path", "des":"method path, same as SetValue", "required":true},
			{ "parameter":"params", "des":"arguments pass to method", "required":false},
			{ "parameter":"toBuffer", "des":"buffer to save results", "required":false}
		],
		"examples":[
			{
				"name":"show method, same as CmdShow command",
				"context":	'' +
						'{<br>' +
						'	"cmd": "CallMethod", <br>' +
						'	"uid":"obj01",<br>' +
						'	"path":"show",<br>' +
						'	"params":false<br>' +
						'}'	
			},
			{
				"name":"get object center and save to buffer",
				"context":	'' +
						'{<br>' +
						'	"cmd": "CallMethod", <br>' +
						'	"uid":"obj01",<br>' +
						'	"path":"GetCenter",<br>' +
						'	"toBuffer":{"ObjectManager":"RunBuffer/curObjectCenter"}<br>' +
						'}'	
			},
			{
				"name":"set timer start time",
				"context":	'' +
						'{<br>' +
						'	"cmd": "CallMethod", <br>' +
						'	"uid":"timer01",<br>' +
						'	"path":"setStartTtime",<br>' +
						'	"params":[2015,8,11,13,55,23,0]<br>' +
						'}'	
			}		
		]
	}
	
]

docCreator.addDocItemFromData("Common Object Interface", cmds)

